# Generated by Django 5.2.5 on 2025-09-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_customuser'),
    ]

    operations = [
    ]
